# Cloudflare Pages Configuration for FairForge
name = "fairforge"
compatibility_date = "2025-10-15"
pages_build_output_dir = "out"

# Note: This configuration is for static deployment only
# FairForge requires server-side API routes which work better on:
# - Vercel (recommended for Next.js)
# - Railway (full-stack apps)
# - Netlify (with functions)